### ISSUE TITLE
Giving option to choose between Gulp or Grunt build system.

### ISSUE THREAD

**Issue by jagandecapri** [yahoo/generator-fluxible#18]
It would be nice if there is an option to choose between Gulp or Grunt system.
I have made one in my fork of the repo.
I would be glad to make a PR for that if it is OK.

**Comment by redonkulus** [comment]
I wouldn't have an issue just switching to Gulp completely. @mridgway thoughts?

**Comment by jagandecapri** [comment]
IMO, it would be better if there is an option. I don't know the stats on how many people are still using Grunt but I think there are still people out there using it.

**Comment by mmahalwy** [comment]
I don't think this is working...

**Comment by redonkulus** [comment]
We have not published it yet. There is another PR open, we will publish after we merge that.

**Comment by redonkulus** [comment]
This is done and published in 1.0.4.

**Comment by redonkulus** [comment]
Thanks to @JoshuaGross for the PR!

**Comment by jagandecapri** [comment]
No problem. Cheers!!! :smiley:
