### ISSUE TITLE
You don't use webpack on the server, therefore any config in webpack will not work

### ISSUE THREAD

**Issue by totty90** [yahoo/generator-fluxible#21]
For example if I set an [alias](http://webpack.github.io/docs/configuration.html#resolve-alias) in the [webpack config](https://github.com/yahoo/generator-fluxible/blob/master/app/templates/webpack.config.js) it will not work in node.js. 

Also if I need to use any image and require it I need to add some loaders: https://github.com/tcoopman/image-webpack-loader but it doesn't work on the server, obviously because uses the node.js require instead of the webpack one.

**Comment by totty90** [comment]
A possible solution is to use enhanced-require

	// Needed for file-loader in webpack.
	GLOBAL.__webpack_public_path__ = '';
	var options = require('./webpack.config');
	// enable for all modules recursivly
	// This replaces the original require function in loaded modules
	options.recursive = true;
	options.originalRequire = require;
	var myRequire = require('enhanced-require')(module, options);
	module.exports = myRequire;


This contents should be added to the start.js and might need some tweaks.

**Comment by mridgway** [comment]
This seems related to using babel with require-ensure: https://github.com/babel/babel-loader/pull/60
