### ISSUE TITLE
Gulp generator does not rebuild webpack on file changes

### ISSUE THREAD

**Issue by totty90** [yahoo/generator-fluxible#23]
- Just created a new project.
 - Add `debugger` at the end of the client.js file. 
 - Now run gulp;
 - Now test in browser with console opened; You will get the breakpoint;
 - Now remove the `debugger` from the client.js file;
 - Wait, refresh your page and you will still get that breakpoint; I need to restart gulp;

In console

	[03:08:01] [nodemon] restarting due to changes...
	[03:08:01] [nodemon] restarting due to changes...
	[03:08:01] [nodemon] starting `node ./start.js`

But the file in the dist doesn't get updated.

Also consider using WebpackDevServer and make a proxy from the server to the WebpackDevServer server. In production will be loaded the built file.

**Comment by totty90** [comment]
Fixed it like this:

webpack:

    module.exports = {
        resolve: {
            extensions: ['', '.js']
        },
        entry: './client.js',
        output: {
            // https://github.com/webpack/webpack-dev-server/issues/88
            path: require("path").resolve("./build/js/"),
            publicPath: '/public/js/',
            filename: '[name].js'
        },
        module: {
            loaders: [
                { test: /\.css$/, loader: 'style!css' },
                { test: /\.js$/, exclude: /node_modules/, loader: require.resolve('babel-loader') },
                { test: /\.json$/, loader: 'json-loader'}
            ]
        },
        stats: {
            colors: true
        },
        devtool: 'source-map',
        watch: true,
        keepalive: true
    };


gulpfile

    var gulp = require('gulp');
    var gutil = require('gulp-util');
    var nodemon = require('gulp-nodemon');
    var webpack = require('gulp-webpack');
    var path = require('path');
    var del = require('del');
    var webpackConfig = require('./webpack.config.js');

    gulp.task('default', ['clean', 'nodemon:app', 'webpack:dev']);

    gulp.task('clean', function (cb) {
        del(['build'], cb);
    });

    gulp.task('nodemon:app', function () {
        nodemon({
          script: './start.js',
          ignore: ['build/**'],
          ext: 'js'
        });
    });

    gulp.task('webpack:dev', ['clean'], function() {
        gulp.src('./client.js')
            .pipe(webpack(webpackConfig, void 0,  function(err, stats) {
    	        err && console.log('ERR:' + err)
    	    }))
       	  	.pipe(gulp.dest('build/js'));
    });


Notes:

 - It's not as fast as I like; I will consider using the webpack dev server;

**Comment by mridgway** [comment]
I'm not an expert on gulp, so it would be good if someone else could look at this.

**Comment by mridgway** [comment]
It looks like we still want to use `gulp-webpack-build` due to the benefits listed [here](http://webpack.github.io/docs/usage-with-gulp.html#use-with-gulp-webpack-build), but we need to hook up the watch command as well.

**Comment by AbrahamAlcaina** [comment]
I created a pull request:
https://github.com/yahoo/generator-fluxible/pull/31
