### ISSUE TITLE
SyntaxError are not readable

### ISSUE THREAD

**Issue by totty90** [yahoo/generator-fluxible#24]
When I have a syntax error this is what I get in the console:

    SyntaxError: E:/Totty/Web/slot-circle/components/Html.js: Unexpected token (10:24)
       8 |     ←[32m}←[39m
       9 |
    > 10 |     ←[37mgetChildContext←[39m←[37m←[1m:←[22m←[39m ←[94m←[1m(←[22m←[39m←[94m←[1m)←[22m←[39m ←[32m{←[39m
         |                         ^
      11 |          ←[36mreturn←[39m ←[32m{←[39m←[37mcontext←[39m←[37m←[1m:←[22m←[39m ←[36mthis←[39m←[37m←[1m.←[22m←[39m←[37mprops←[39m←[37m←[1m.←[22m←[39m←[37mcontext←[39m←[32m}←[39m
      12 |     ←[32m}←[39m
      13 |
        at raise (E:\Totty\Web\slot-circle\node_modules\babel\node_modules\acorn-babel\acorn_csp.js:343:15)
    ....

Can you see all these ` ←[36m`? are very annoying..

**Comment by mridgway** [comment]
I don't see these characters in the output. It seems that your terminal does not accept color codes, but Fluxible doesn't do anything with colors in console logs or warnings.

**Comment by totty90** [comment]
Strange because I get correct colors with gulp/grunt/webpack... Only with fluxible I get this, it might be something with the build process. I'm on win8 64bit
