### ISSUE TITLE
ApplicationStore doesn't call emitChange within handlePageTitle

### ISSUE THREAD

**Issue by jeffhandley** [yahoo/generator-fluxible#25]
Changes to the store (through the UPDATE_PAGE_TITLE/handlePageTitle handler) are then not reflected in components.

**Comment by jeffhandley** [comment]
By the way, this fix does make the client-side work (despite not fixing the server-side in #27).  Extending this sample to have the client execute the action for updating the page title, the page title does get changed.

**Comment by redonkulus** [comment]
Thanks @jeffhandley we are taking a look at fixing the server side issue now.
