### ISSUE TITLE
Page Title Doesn't Get Set on the Server

### ISSUE THREAD

**Issue by jeffhandley** [yahoo/generator-fluxible#27]
In [Html.js](https://github.com/yahoo/generator-fluxible/blob/master/app/templates/components/Html.js#L11), the `ApplicationStore` hasn't been updated with a page title yet, so the `title` renders as empty from the server.

**Comment by redonkulus** [comment]
I'm assuming this fixes it? https://github.com/yahoo/generator-fluxible/pull/26

**Comment by jeffhandley** [comment]
No, it doesn't.  I've not yet dug in to see why it doesn't though, as I expected it would too.  Not sure I'll be able to figure this one out.
