### ISSUE TITLE
About css loader

### ISSUE THREAD

**Issue by tom76kimo** [yahoo/generator-fluxible#40]
Hi, I intend to use this to create a site and noticed the css loader seems to be not working.

I simply added a css file and import './style.css' in my `Html.js`. But got syntax error after the start.js rebuilt by nodemon.

Is the `require('babel/register');` in `start.js` not supporting css-loader? Or is there a way to use css-loader?

**Comment by mridgway** [comment]
Server-side require does not support css. We should probably remove the css-loader from the generated webpack config by default to stop confusion. You can try to use something like https://github.com/webpack/enhanced-require to allow it to work or you could try using webpack to bundle your server code as well.

**Comment by redonkulus** [comment]
Removed here https://github.com/yahoo/generator-fluxible/pull/41

**Comment by tom76kimo** [comment]
:+1:  thanks guys!

**Comment by brandondurham** [comment]
I'd love to learn more about bundling for the server with Webpack. Could you point me to a good resource, or make a suggestion on how to get started in this generator?

**Comment by mridgway** [comment]
@brandondurham I haven't done bundling for the server yet, but there was a blog post by James Long a few months ago that talked about it: http://jlongster.com/Backend-Apps-with-Webpack--Part-I

**Comment by brandondurham** [comment]
Ha! So I actually followed that three-part post to get started. Just yesterday.

Thanks for the response.
