### ISSUE TITLE
App is blank, other commands behaves strangely...

### ISSUE THREAD

**Issue by hackhat** [yahoo/generator-fluxible#44]
If I follow all the instructions and I run `npm run dev` I get a blank page... If I do `npm start` I get a broken page with only 2 links (home and about) but it fails to load the `main.js` file. If I do `npm run build` there is no index.html...

I don't know what is going on, but the `npm run dev` says that it's listening on port 3000 and rebuilds every time I change a file.

I'm on win 10, 64 bit, using the current versions of the tools, on a clean machine.

**Comment by hackhat** [comment]
First of all you need to install nodemon with this command: `npm install -g nodemon`;

So, to run on windows you have to open 2 cmd. In the first one you run this command:

 - `node webpack-dev-server.js`;

In the 2nd cmd window you have to run:

 - `set PORT=3001`;
 - `nodemon start.js -e js,jsx`;

I think this should be added to the docs, but probably there is a way to do all this with just 1 cmd.

**Comment by mridgway** [comment]
Hmm, I haven't played around with this on Windows yet, but I'll try to spend some time getting it to work with one command. Want to open a PR to add a note for Windows to the README for now?

**Comment by xiongxin** [comment]
I'm on win 7,64 bit, using the newest version of the tools
when i run `npm run dev`,i get blank page too.

**Comment by mridgway** [comment]
This repo has been moved to the Fluxible monorepo: https://github.com/yahoo/fluxible/tree/master/packages/generator-fluxible. I created an issue there to keep this on track: https://github.com/yahoo/fluxible/issues/280
