### ISSUE TITLE
Can't install 3rd party jsx components

### ISSUE THREAD

**Issue by timothyjlaurent** [yahoo/generator-fluxible#6]
I have been trying to get react-autcomplete installed in a yo fluxible project.

React-autocomplete is uses the `.js` extension so I changed the loader to 

```
 40                 },
 41                 module: {
 42                     loaders: [
 43                         { test: /\.css$/, loader: 'style!css' },
 44                         { test: /\.jsx?$/, loader: 'jsx-loader' },
 45                         { test: /\.json$/, loader: 'json-loader'}
 46                     ]
 47                 },
```

Whenever I do this  I get 

```
[nodemon] starting `node ./server.js`
 70% 20/20 build modules
/Users/tlaurent/dev/test/node_modules/react-autocomplete/lib/combobox.js:358
      <div className={this.getClassName()}>
      ^
SyntaxError: Unexpected token <
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/tlaurent/dev/test/node_modules/react-autocomplete/lib/main.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[nodemon] app crashed - waiting for file changes before starting...
```

If you do a blank project it gets built just fine.

**Comment by timothyjlaurent** [comment]
Ok... so I have been getting help with this on the Webpack gitter chat... At their suggestion I extracted a webpack.config.js out and ran webpack and it builds fine.

How could we fix the generator so that it can automatically build 3rd party JSX without failing?

**Comment by redonkulus** [comment]
Did you have to change anything in your webpack config to get it to build?

**Comment by timothyjlaurent** [comment]
no, I also have a gulp version that is working now... It seems to be a problem with the grunt loader

**Comment by timothyjlaurent** [comment]
To clarify I just took the webpack:dev object and put it in a webpack.conf.js unchanged.

[Here is a link to the working gulpfile I made:](https://github.com/timothyjlaurent/fluxible-variants/blob/master/Gulpfile.js) It had to be tweaked a bit to get in building correctly and to get debugging working but I think it is good now.

**Comment by jedireza** [comment]
Nice. Glad you got it working. Thanks for sharing the link.

**Comment by timothyjlaurent** [comment]
How is this a closed issue??
You cannot use the fluxible-generator  and require 3rd party JSX components. Me solving it doesn't fix the issue.

**Comment by jedireza** [comment]
Oh my apologies. Would you like to open a PR implementing your fix?

**Comment by timothyjlaurent** [comment]
I'd be happy to but my fix is on the output of the the yo generator no on the generator script itself. For me it will be good enough to make a new 'base-project' that I can clone. Also, I switched the build engine from grunt to gulp (Which could be seen as an upgrade). _Would this be something you'd consider merging were I to make it. _
The Yeoman script looks simple enough-- I'm sure I could plug in my changes.  
I think this important because this bug presents a significant barrier to using Fluxible when you discover that you can't add other components from the React community to your application.

**Comment by jedireza** [comment]
It get's messy mixing `.jsx` and `.js` extensions. Especially when the `.js` extension is actually a JSX file. You can indeed make sharable React components without using JSX. My personal opinion is, if a file is using JSX, it should have the `.jsx` extension.

On the server side, `node-jsx` only supports installing on one extension. So you're either using one or the other. As seen here:
https://github.com/petehunt/node-jsx/blob/6e52f5a1a0df17818df8b9ddcf7cf48803eb406f/index.js#L16

There's even an issue open in the `react-autocomplete` about this:
https://github.com/rackt/react-autocomplete/issues/10

Since you know why this is happening, you may want to close or update your issue in that repo also:
https://github.com/rackt/react-autocomplete/issues/21

- - - - -

So I'm not sure if this is something we need to handle, or even could be totally solved, in our generator.

**Comment by timothyjlaurent** [comment]
I agree that .jsx is much more clear -- but one thing I uncovered is that it isn't just the extension that is causing the issue. 

If you change the extension of the react-autocomplete jsx files to .jsx it still won't build with grunt-webpack . 

So it appears that this bug affects any 3rd party react components in the node-modules folder

Again running Webpack outside of Grunt doesn't have this problem, and I have it building with Gulp-webpack as well.

**Comment by timothyjlaurent** [comment]
One thought is that perhaps Babel might be the answer instead of using jsx-loader and node-jsx. 

I have used it with a toy flummox app I am making and it works great for the browser. 

There are also ways to get the babel transpiler to work with node. 

So far it seems awesome.
